name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 22.16

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --legacy-peer-deps

      - name: Build
        run: |
          npm run build
        env:
          CI: true

      - name: Test
        run: |
          npm run test --if-present
        env:
          CI: true

      - name: Prepare and deploy
        run: |
          npm run deploy -- --name="Swimlane" --email="swimlane-devops@swimlane.com"
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
